config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'auth_confirm_email', to: 'omniauth_callbacks#auth_confirm_email'
  end

  concern :votable do
    put :vote_up, on: :member
    put :vote_down, on: :member
    delete :destroy_vote, on: :member
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      post :best_answer, on: :member
    end
  end

  resources :attachments, only: [:destroy]
  root to: 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  default_scope { order ('created_at DESC') }

  has_many :answers, dependent: :destroy
  belongs_to :user
  validates :title, :body, presence: true
  validates :title, length: { in: 5..140 }

  after_save :up_owner_reputation

  def has_the_best_answer?
    answers.exists?(best: true) ? true : false
  end

  def up_owner_reputation
    user.change_reputation(YOU_PLACED_QUESTION_OR_ANSWER)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    respond_with @question = Question.find(params[:id])
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    authorize @question
    respond_with @question
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  after_action :publish_question, only: [:create]

  respond_to :html

  def index
    respond_with @questions = Question.all

  end

  def new
    @question = Question.new
    @question.attachments.build
  end

  def show
    @answer = @question.answers.build
    @answer.attachments.build
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def edit; end

  def update
    authorize @question
    @question.update(question_params)
    respond_with @question, location: @question
  end

  def destroy
    authorize @question
    respond_with @question.destroy
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions',
                                 {question: @question, question_user: @question.user})
  end
end

app/views/questions/_form.html.slim
section.aks-question-sect.container
  .ask-question-wrapper
    h1.ask-question-title
      -if controller.action_name == 'new'
        |Задайте вопрос
      -else
        | Редактировать вопрос
    = form_for @question, class: 'ask-question-form' do |f|
      .all-form-inputs-errors
        = render 'commons/errors', resource: @question
      .ask-question-form-inputs
        = f.label 'Заголовок вопроса'
        = f.text_field :title
      .ask-question-form-desc
        = f.label 'Описание вопроса'
        = f.text_area :body
      = render 'attachments/attachments_added', f: f, obj: @question

      .ask-question-form-subm
        - if controller.action_name == 'new'
          = f.button 'Разместить вопрос на сайте'
        - else
          = f.button 'Обновить вопрос'

app/views/questions/_question.html.slim
article.all-questions_current-question
  .all-questions_current-question__user-avatar
    = link_to
      = image_tag('default-avatar.png')
  .question-user-title
    |Вопрос пользователя #{question.user.email}
    .question_votes-wrapper
      span.current-question-answer-votes
        = render 'votes/vote',votable: question
  h2.all-questions__current-question-title
    = link_to question, class: 'all-questions__current-question-title-link'
      | #{question.title}
  .all-questions__current-question-body
    p
      | #{question.body}
    span.all-questions__current-question-answers-count
      = link_to question
        i.material-icons.md-18
          |comment
        |#{question.answers.count} Ответов
    -if user_signed_in? && current_user.author_of?(question)
      span.all-questions__current-question-answer-destroy
        = link_to question, method: :delete
          i.material-icons.md-18
            |delete
          | Удалить вопрос
      span.all-questions__current-question-answer-edit
        = link_to edit_question_path(question)
          i.material-icons.md-18
            |mode_edit
          | Редактировать вопрос

app/views/questions/edit.html.slim
=render 'questions/form'

app/views/questions/index.html.slim
section.all-questions.container
  .all-questions-articles-wrapper
    h1.all-questions-title
      |Список вопросов
    .articles-all-questions-wrapper
      - @questions.each do |question|
        = render 'questions/question', question: question
  = render 'commons/signed_signup_buttons'

app/views/questions/new.html.slim
= render 'questions/form'

app/views/questions/show.html.slim
section.single-question-show.container
  .single-question-and-his-answers
    article.single-question  data-question_id="#{@question.id}"
      .single-question__user-avatar
        = link_to
          = image_tag('default-avatar.png')
      .question-user-title
        |Вопрос пользователя #{@question.user.email}
        .question_votes-wrapper
          span.current-question-answer-votes
            = render 'votes/vote',votable: @question

      h3.single-question-title
        |#{@question.title}
      .single-question-body
        p
          |#{@question.body}

      .single-question-attachments-files-wrapper
        -unless @question.attachments.blank?
          p
            |Прикрепленные файлы
          ul.single-question-attached-files-list
            -@question.attachments.each do |a|
              = render 'attachments/show_attachments', a: a, subject: @question

      -if policy(@question).update?
        span.all-questions__current-question-answer-destroy
          = link_to @question, method: :delete
            i.material-icons.md-18
              |delete
            | Удалить вопрос

        span.all-questions__current-question-answer-edit
          = link_to edit_question_path(@question)
            i.material-icons.md-18
              |mode_edit
            | Редактировать вопрос

      = render 'comments/comments', parent: @question

    .single-question-answers__all-answers
      h2.single-question-answers__all-answers-title
        | Ответы  на вопрос
      =render @question.answers

    .single-question-answers__add-answer-for-question
      -if user_signed_in?
        = render 'answers/form'
  = render 'commons/signed_signup_buttons'