config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'auth_confirm_email', to: 'omniauth_callbacks#auth_confirm_email'
  end

  concern :votable do
    put :vote_up, on: :member
    put :vote_down, on: :member
    delete :destroy_vote, on: :member
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      post :best_answer, on: :member
    end
  end

  resources :attachments, only: [:destroy]
  root to: 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Votable
  include Commentable
  include Constants

  default_scope { order ('best DESC , created_at ASC') }

  belongs_to :question
  belongs_to :user
  validates :body, presence: true

  after_save :up_owner_reputation

  def set_best
    Answer.transaction do
      if question.has_the_best_answer?
        answer = question.answers.find_by(best: true)
        answer.update!(best: false)
      end
      update!(best: true)
    end
  end

  def up_owner_reputation
    user.change_reputation(YOU_PLACED_QUESTION_OR_ANSWER)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:update, :destroy, :best_answer]
  after_action :publish_answer, only: [:create]

  respond_to :js, :json

  def create
    respond_with @answer = @question.answers.create(answer_params.merge(user: current_user))
  end

  def edit
  end

  def update
    authorize @answer
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    authorize @answer
    respond_with @answer.destroy
  end

  def best_answer
    authorize @answer
    @answer.set_best
    respond_with @answer, location: @answer.question
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast("questions/#{@answer.question.id}/answers",
                                 {answer: @answer, answer_user: @answer.user, attachments: @answer.attachments})
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  def index
    @answers = Answer.all
    respond_with @answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params.merge(user: current_resource_owner))
    authorize @answer
    respond_with @answer
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  article.single-question-answers__current_answer id="current_answer-#{answer.id}"
    .single-question__user-avatar
      = link_to
        = image_tag('default-avatar.png')

    .single-question-answers__current-answer-wrapper_for-arrtibutes
      - if answer.best
        span.single-question-answers__current-answer_best_answer
          |Автор отметил ответ, как лучший
      - elsif policy(answer).best_answer?
          span.single-question-answers__current-answer_best_answer
            = link_to best_answer_answer_path(answer), method: :post
              |Лучший ответ
              i.material-icons.md-18
                |favorite_border

      span.current-question-answer-votes
        =render 'votes/vote', votable: answer
    .single-question-answers__current-answer-title_wrapper
      h2.single-question-answers__current-answer-title
        |Ответ пользователя #{answer.user.email}

    .single-question-answers__current-answer-body
      p id="answer-#{answer.id}"
        |#{answer.body}

    .single-question-attachments-files-wrapper
      - unless answer.attachments.blank?
        p
          |Прикрепленные файлы
        ul.single-question-attached-files-list
          - answer.attachments.each do |a|
            = render 'attachments/show_attachments', a: a, subject: answer

    - if policy(answer).update?
      =form_for answer, remote: true, html: { class: 'current-answer-edit-form',
                                id: "update-answer-form-#{answer.id}" } do |f|
        .error-answer-update-messages
        =f.text_area :body, class: 'edit_answer'
        = render 'attachments/attachments_added', f: f, obj: answer
        =f.submit 'Обновить ответ', class: 'update-current-answer-button'

      span.all-questions__current-question-answer-destroy
        = link_to answer_path(answer),method: :delete, remote: true,
                data: { answer_id: answer.id}, class: 'delete-curent-answer'
          i.material-icons.md-18
            |delete
          | Удалить ответ
      span.all-questions__current-question-answer-edit
        = link_to nil, remote: true,
                data: { answer_id: answer.id }, class: 'current-answer-link-edit'
          i.material-icons.md-18
            |mode_edit
          |Редактировать ответ

    = render 'comments/comments', parent: answer

app/views/answers/_form.html.slim
= form_for [@question, @answer], remote: true, method: :post,
        class: 'add-answer-form' do |f|
  .all-form-inputs-errors
  .answer-desk
    = f.label 'Текст ответа'
    = f.text_area :body, id: 'add-answer-body'
    = render 'attachments/attachments_added', f: f, obj: @answer
  .add-answer-form-subm
    = f.button 'Разместить ответ'

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $("div.all-form-inputs-errors").html(
        "<p> Исправьте следующие ошибки и попробуйте снова:</p>" +
            "<%= j message.split(' ')[1..-1].join(' ') %>"
        );
  <% end %>
<% else %>
  $("div.all-form-inputs-errors").html("");
  $('.single-question-answers__all-answers').append("<%= j render @answer  %>");
  $('#add-answer-body').val('');
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $(".error-answer-update-messages").html(
        "<p> Исправьте следующие ошибки и попробуйте снова:</p>" +
        "<%= j message.split(' ')[1..-1].join(' ') %>"
    );
  <% end %>
<% else %>
  $('.single-question-answers__all-answers').html("<%= j render @question.answers %>");
<% end %>