config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'auth_confirm_email', to: 'omniauth_callbacks#auth_confirm_email'
  end

  concern :votable do
    put :vote_up, on: :member
    put :vote_down, on: :member
    delete :destroy_vote, on: :member
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      post :best_answer, on: :member
    end
  end

  resources :attachments, only: [:destroy]
  root to: 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .flashmsg
      | #{msg}

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Questions - Answers
    = Gon::Base.render_data
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = action_cable_meta_tag
    = csrf_meta_tags

  body
    header.main-header
      .menu-sec-wrapper
        section.container.menu-sec
          div.site-logo
            = link_to root_url
              | QUESTIONS
          nav.top-site-nav
            ul
              li.current-nav-page
                = link_to new_question_path
                  | Задать вопрос
              li.current-nav-page
                = link_to questions_path
                  | Все вопросы
              li.current-nav-page
                = link_to questions_path
                  | Профайл
      .section.ask-question-main.container
        .ask-question
          = link_to new_question_path, class: 'ask-button'
            | Задать вопрос

      .section.search
        = form_for :search, url: search_path, method: :get do |f|
          = f.text_field :query, value: params[:query]
          = f.select :target, [['Везде', 'everywhere'], ['В вопросах', 'questions'],
                  ['В ответах', 'answers'], ['В комментариях', 'comments'],
                  ['В пользователях', 'users']], {selected: params[:target]}
          = f.submit 'Поиск'
    = yield